# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-2bebb5fe-73dc-4ea2-80b2-af631e3ce6e4";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2bebb5fe-73dc-4ea2-80b2-af631e3ce6e4".device = "/dev/disk/by-uuid/2bebb5fe-73dc-4ea2-80b2-af631e3ce6e4";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D5A5-D7D8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/dbca66c3-d28b-4112-81c6-ed93b92f3fb3"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
